### ISSUE TITLE
This function is causing absurd memory leaks

### ISSUE THREAD

**Issue by fil7er** [Hardikb19/rotating-widgets#2]
The function RotatingWidget() is trying to setState of widget that no longer exists after removing the Navigation Route, in a loop. 

`E/flutter ( 6857): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: setState() called after dispose(): _RotatingWidgetState#9742b(lifecycle state: defunct, not mounted)
E/flutter ( 6857): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter ( 6857): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter ( 6857): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter ( 6857): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1231:9)
E/flutter ( 6857): #1      State.setState (package:flutter/src/widgets/framework.dart:1266:6)
E/flutter ( 6857): #2      _RotatingWidgetState._animationSequence.<anonymous closure> (package:rotating_widgets/rotating_widgets.dart:107:9)
E/flutter ( 6857): #3      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter ( 6857): #4      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter ( 6857): #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter ( 6857): #6      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1207:26)
E/flutter ( 6857): #7      _rootRunUnary (dart:async/zone.dart:1370:13)
E/flutter ( 6857): #8      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter ( 6857): #9      _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1191:26)
E/flutter ( 6857): #10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter ( 6857): #11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter ( 6857): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter ( 6857): 
`

**Comment by Hardikb19** [comment]
A new PR has been published, if this problem still persists, continue this thread, I will look into this.
Thank you for bringing this to my notice :)

**Comment by fil7er** [comment]
The last PR fixed it, thanks
